services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - AUTHORIZED_USER_ID=${AUTHORIZED_USER_ID}
      - VEHICLE_VIN=${VEHICLE_VIN}
      - RENAULT_EMAIL=${RENAULT_EMAIL}
      - RENAULT_PASSWORD=${RENAULT_PASSWORD}
    volumes:
      - ./.env:/app/.env
